sudo: false
language: node_js
install: true
script: ./test/travis.sh
env:
  matrix:
  - NODE=6
  - NODE=5
  - NODE=4
  - BROWSER=chrome
  - BROWSER=firefox
  - BROWSER=safari
  - BROWSER=android
  - BROWSER=iphone
  global:
  - secure: YBOE4p2JIsTZ8YfjtEsjLxOWIpjEmNNv1ng6q7At4k/WF00cPJJLZCdsL3/XsXrQWD0EApEvAE/8yTu/2pMMsgyV54FLYKTtRQgdUqqPbEivRjL5Sv9TF0sdWo+GwaW1WrBtr4yTjVSmj5ILpk2jDSzMsnIwrt6rA8E8HS8U60ZL/Vip2fFKCR7dqix4NlP300L4ePQWJ8GXYfCmaaAqQc1+q5aw8PlM6bkhJSvBj7LfBAzZca3oTvtiZXWoN9Kcs1m4d96WLUh/UZxZRYuwRrsg5ByhyDUJPHH/k+tnmIkiEVoKPgg85FYdwBfBrqq14kPnwAHSQ4ap7LseUMmaSABGMbmK0wdoi7yaqNon69w+z9mL/G6HmE8ADxeIrKHKhyp5NJH+uIyU8UysMnkijwFpDyrOaAr5zCyPt1zVXaxJWcjpCoilYwcTmZA9sHdMf4jPWI9Xkxz5/HPPsc7Ae9eCFwrl2OfBzvCUiZcHmRgylVAmbYSbEQIjoQwu4EIFfz1/bO8G5PNKL16D0eDB009ocOQSCRHFEwFXUaKe6CptArkH91FDGtvTsGV5OCUOojUi/FT87pHrC13t+ajHvblK7OjorL8doTNRpJmCT4zrZUprD1KxcgG4AInXoZr6eBlrUO0vBl9Poc0Oq79JMrQVxEhLEtKR4y0O+Hs0Xko=
  - secure: eZhtUOsHMpR6i54St2JEZ0TKiW2eOfAsQkWdmYu594xdFwKpPhp9Nu0U/ec5gRGUNe3bIUxcOE9wnPTXUmznqDUtmT20N1vaLmtazDAitsAAcmOo7cSl2s6tFVjEbJPC7KbdVlyd9sIOMgP4Gb11VsUxRgTkYSKcCP/9u4zC9iavID7+hPgnm2aMIat4X8NgzP68jj8qmQN5f6mOIlDPtUKwZTNk9xmEO0kKQVWBrTll8a/DxQjUfiLL2UfVyhHFa8yr6oO1S6VCFhvyFoOQvAN1pwSko3EDHvy0Ody16EBEwTilRhTImD5bu/Ty6sEgmT2OV0hpP74MJV12hZ16keUwdpzCM/CuTfKvOhogNSRZ7tZaa3TqzUaokey/b/D0SkU5PLwWePlObUTmGEPA8GADF0bfDZrqplaaK6b1zMaoqe/71ehekxLSMEGtEElkjcnkFr4lSQWTU7wGtwrTXFY4T0MHv4f4Gr24daCIyrXRuCRieimyVIfMU7hEzuWmPimgGy9VS8ujLX8s+P+xR98SzToy5/t1FbyJIgZW+9FyPCZbdurhidCsJKOg3cNjeHSh7OG7S//6TtCcvqq+OxoYA3CHVcAb1BJb217Dkuu48HrqVWpSKmwVyRg15dDJp3sux7jM67s4/16rK7HJqmEyF2AJhtkwQRPbbsLTBRY=
notifications:
  email: false
